packages:
  - .

verifyDepsBeforeRun: false

onlyBuiltDependencies:
  - electron
  - esbuild
  - '@swc/core'

allowBuilds:
  esbuild: true

minimumReleaseAgeExclude:
  - '@react-pdf/font@4.0.9'
  - '@react-pdf/image@3.1.1'
  - '@react-pdf/layout@4.7.0'
  - '@react-pdf/pdfkit@6.0.0'
  - '@react-pdf/render@4.6.0'
  - '@react-pdf/renderer@4.6.0'
  - '@react-pdf/stylesheet@6.2.2'
  - '@react-pdf/textkit@6.4.0'
  - '@react-pdf/types@2.11.2'
