#!/usr/bin/env node
/**
 * gen_ui_config.mjs —— UI 配置生成器（设计阶段产物）
 * 读 ui-config/ 各维度 TS 配置（Node 24 原生 type stripping）→ 生成 CSS 变量文件
 * `project/src/renderer/src/ui-config.generated.css`（:root 内 --ui-* 变量，构建期消费）。
 * 用法：`node scripts/gen_ui_config.mjs`（build/dev 已自动前置本脚本）。
 * 渲染层不 import ui-config/ 任何源文件——只消费本生成产物。
 */
import { writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { uiLayout } from '../ui-config/layout.ts'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const out = resolve(root, 'project/src/renderer/src/ui-config.generated.css')

const vars = [
  ['--ui-list-max-width', `${uiLayout.listMaxWidth}px`],
  ['--ui-list-gap', `${uiLayout.listGap}px`],
  ['--ui-card-padding-x', `${uiLayout.cardPaddingX}px`],
  ['--ui-card-padding-y', `${uiLayout.cardPaddingY}px`],
  ['--ui-module-grid-gap', `${uiLayout.moduleGridGap}px`],
]

const css = `/* AUTO-GENERATED by scripts/gen_ui_config.mjs — 勿手改；改 ui-config/ 后重跑生成器 */
:root {
${vars.map(([k, v]) => `  ${k}: ${v};`).join('\n')}
}
`

writeFileSync(out, css)
console.log(`gen_ui_config: wrote ${out} (${vars.length} vars)`)
